name: Deploy to Dreamhost
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Build
        run: npm run build
        env:
          PUBLIC_URL: https://badasspoet.com

      - name: List output directories
        run: |
          echo "Contents of .next:"
          ls -la .next
          echo "Contents of out (if exists):"
          ls -la out || echo "out directory does not exist"

      - name: Deploy to Dreamhost via SFTP
        uses: pressidium/lftp-mirror-action@v1
        with:
          host: pdx1-shared-a1-25.dreamhost.com
          user: dh_2bzpfx
          pass: ${{ secrets.FTP_PASSWORD }}
          localDir: ./.next
          remoteDir: /home/dh_2bzpfx/badasspoet.com
