name: Deploy to Dreamhost
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build
        env:
          PUBLIC_URL: https://badasspoet.com

      - name: Deploy to Dreamhost via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: pdx1-shared-a1-25.dreamhost.com
          username: dh_2bzpfx
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_path: ./build/*
          remote_path: /home/dh_2bzpfx/badasspoet.com/
          sftpArgs: '-o StrictHostKeyChecking=no' 